[dependencies]
advapi32-sys = "0.2.0"
aho-corasick = "0.5.3"
ansi_term = "0.9.0"
bitflags = "0.7.0"
byteorder = "0.5.3"
cfg-if = "0.1.0"
chrono = "0.2.25"
clap = "2.18.0"
cookie = "0.3.1"
crossbeam = "0.2.10"
docopt = "0.6.86"
dtoa = "0.2.2"
either = "1.0.1"
enum_primitive = "0.1.0"
env_logger = "0.3.5"
flate2 = "0.2.14"
gcc = "0.3.38"
gdi32-sys = "0.2.0"
getopts = "0.2.14"
gl_generator = "0.5.2"
glob = "0.2.11"
hpack = "0.3.0"
httparse = "1.2.0"
hyper = "0.9.12"
idna = "0.1.0"
itertools = "0.5.5"
itoa = "0.1.1"
kernel32-sys = "0.2.2"
khronos_api = "1.0.0"
language-tags = "0.2.2"
lazy_static = "0.2.1"
libc = "0.2.17"
libz-sys = "1.0.6"
log = "0.3.6"
matches = "0.1.4"
memchr = "0.1.11"
mime = "0.2.2"
miniz-sys = "0.1.7"
net2 = "0.2.26"
nix = "0.7.0"
nom = "1.2.4"
num = "0.1.36"
num-bigint = "0.1.35"
num-complex = "0.1.35"
num-integer = "0.1.32"
num-iter = "0.1.32"
num-rational = "0.1.35"
num-traits = "0.1.36"
num_cpus = "1.1.0"
phf = "0.7.19"
phf_shared = "0.7.19"
pkg-config = "0.3.8"
post-expansion = "0.1.0"
quote = "0.3.5"
rand = "0.3.14"
regex = "0.1.80"
regex-syntax = "0.3.9"
rust-crypto = "0.2.36"
rustc-serialize = "0.3.21"
rustc_version = "0.1.7"
semver = "0.5.1"
semver-parser = "0.6.1"
serde = "0.8.17"
serde_codegen = "0.8.17"
serde_codegen_internals = "0.10.0"
serde_json = "0.8.3"
slab = "0.3.0"
solicit = "0.4.4"
strsim = "0.5.1"
syn = "0.9.2"
syntex = "0.48.0"
syntex_errors = "0.48.0"
syntex_pos = "0.48.0"
syntex_syntax = "0.48.0"
tempdir = "0.3.5"
term = "0.4.4"
term_size = "0.2.1"
thread-id = "3.0.0"
thread_local = "0.3.0"
time = "0.1.35"
toml = "0.2.1"
traitobject = "0.0.3"
typeable = "0.1.2"
typemap = "0.3.3"
unicase = "1.4.0"
unicode-bidi = "0.2.3"
unicode-normalization = "0.1.2"
unicode-segmentation = "0.1.2"
unicode-width = "0.1.3"
unicode-xid = "0.0.3"
unreachable = "0.1.1"
unsafe-any = "0.4.1"
url = "1.2.3"
user32-sys = "0.2.0"
utf8-ranges = "0.1.3"
uuid = "0.3.1"
vec_map = "0.6.0"
void = "1.0.2"
winapi = "0.2.8"
winapi-build = "0.1.1"
ws2_32-sys = "0.2.1"
xml-rs = "0.3.4"

[package]
authors = ["The Rust Playground"]
name = "playground"
version = "0.0.1"
