[package]
name = "playground"
version = "0.0.1"
authors = ["The Rust Playground"]
[profile.dev]
codegen-units = 1
incremental = false

[profile.release]
codegen-units = 1
incremental = false

[dependencies]
MacTypes-sys = "=2.1.0"
adler32 = "=1.0.3"
aho-corasick = "=0.6.10"
ansi_term = "=0.11.0"
arrayvec = "=0.4.10"
atty = "=0.2.11"
autocfg = "=0.1.2"
backtrace = "=0.3.14"
backtrace-sys = "=0.1.28"
base64 = "=0.10.1"
bit-set = "=0.4.0"
bit-vec = "=0.4.4"
bitflags = "=1.0.4"
build_const = "=0.2.1"
byteorder = "=1.3.1"
bytes = "=0.4.11"
cc = "=1.0.29"
cfg-if = "=0.1.6"
chrono = "=0.4.6"
clap = "=2.32.0"
cloudabi = "=0.0.3"
color_quant = "=1.0.1"
crc = "=1.8.1"
crc32fast = "=1.1.2"
crossbeam = "=0.7.1"
crossbeam-channel = "=0.3.8"
crossbeam-deque = "=0.7.1"
crossbeam-epoch = "=0.7.1"
crossbeam-queue = "=0.1.2"
crossbeam-utils = "=0.6.5"
csv = "=1.0.5"
csv-core = "=0.1.5"
data-encoding = "=2.1.2"
debug_unreachable = "=0.1.1"
deflate = "=0.7.19"
dtoa = "=0.4.3"
either = "=1.5.1"
encoding_rs = "=0.8.16"
env_logger = "=0.6.0"
error-chain = "=0.12.0"
filetime = "=0.2.4"
fixedbitset = "=0.1.9"
flate2 = "=1.0.6"
fnv = "=1.0.6"
foreign-types = "=0.3.2"
foreign-types-shared = "=0.1.1"
fuchsia-cprng = "=0.1.1"
fuchsia-zircon = "=0.3.3"
fuchsia-zircon-sys = "=0.3.3"
futf = "=0.1.4"
futures = "=0.1.25"
futures-cpupool = "=0.1.8"
gcc = "=0.3.55"
gif = "=0.10.1"
glob = "=0.2.11"
h2 = "=0.1.16"
html5ever = "=0.18.0"
http = "=0.1.16"
httparse = "=1.3.3"
humantime = "=1.2.0"
hyper = "=0.12.24"
hyper-tls = "=0.3.1"
idna = "=0.1.5"
image = "=0.21.0"
indexmap = "=1.0.2"
inflate = "=0.4.5"
iovec = "=0.1.2"
itertools = "=0.8.0"
itoa = "=0.4.3"
jpeg-decoder = "=0.1.15"
kernel32-sys = "=0.2.2"
language-tags = "=0.2.2"
lazy_static = "=1.2.0"
lazycell = "=1.2.1"
libc = "=0.2.49"
libflate = "=0.1.20"
lock_api = "=0.1.5"
log = "=0.4.6"
lzw = "=0.10.0"
mac = "=0.1.1"
markup5ever = "=0.3.2"
matches = "=0.1.8"
memchr = "=2.2.0"
memmap = "=0.7.0"
memoffset = "=0.2.1"
mime = "=0.3.13"
mime_guess = "=2.0.0-alpha.6"
miniz-sys = "=0.1.11"
miniz_oxide = "=0.2.1"
miniz_oxide_c_api = "=0.2.1"
mio = "=0.6.16"
miow = "=0.2.1"
native-tls = "=0.2.2"
net2 = "=0.2.33"
new_debug_unreachable = "=1.0.2"
nodrop = "=0.1.13"
num = "=0.2.0"
num-bigint = "=0.2.2"
num-complex = "=0.2.1"
num-derive = "=0.2.4"
num-integer = "=0.1.39"
num-iter = "=0.1.37"
num-rational = "=0.2.1"
num-traits = "=0.2.6"
num_cpus = "=1.10.0"
openssl-probe = "=0.1.2"
ordermap = "=0.3.5"
owning_ref = "=0.4.0"
parking_lot = "=0.7.1"
parking_lot_core = "=0.4.0"
percent-encoding = "=1.0.1"
petgraph = "=0.4.13"
phf = "=0.7.24"
phf_codegen = "=0.7.24"
phf_generator = "=0.7.24"
phf_shared = "=0.7.24"
pkg-config = "=0.3.14"
png = "=0.14.0"
precomputed-hash = "=0.1.1"
proc-macro2 = "=0.4.27"
quick-error = "=1.2.2"
quote = "=0.6.11"
rand = "=0.6.5"
rand_chacha = "=0.1.1"
rand_core = "=0.4.0"
rand_hc = "=0.1.0"
rand_isaac = "=0.1.1"
rand_jitter = "=0.1.3"
rand_os = "=0.1.2"
rand_pcg = "=0.1.2"
rand_xorshift = "=0.1.1"
rayon = "=1.0.3"
rayon-core = "=1.4.1"
rdrand = "=0.4.0"
regex = "=1.1.0"
regex-syntax = "=0.6.5"
remove_dir_all = "=0.5.1"
reqwest = "=0.9.10"
ring = "=0.14.6"
rustc-demangle = "=0.1.13"
rustc-serialize = "=0.3.24"
rustc_version = "=0.2.3"
ryu = "=0.2.7"
safe-transmute = "=0.10.1"
same-file = "=1.0.4"
schannel = "=0.1.15"
scoped_threadpool = "=0.1.9"
scopeguard = "=1.0.0"
select = "=0.4.2"
semver = "=0.9.0"
semver-parser = "=0.9.0"
serde_derive = "=1.0.88"
serde_urlencoded = "=0.5.4"
siphasher = "=0.2.3"
slab = "=0.4.2"
smallvec = "=0.6.9"
spin = "=0.5.0"
stable_deref_trait = "=1.1.1"
string = "=0.1.3"
string_cache = "=0.6.2"
string_cache_codegen = "=0.4.2"
string_cache_shared = "=0.3.0"
strsim = "=0.8.0"
synom = "=0.11.3"
syslog = "=4.0.1"
tar = "=0.4.20"
tempdir = "=0.3.7"
tempfile = "=3.0.7"
tendril = "=0.3.1"
term = "=0.5.1"
termcolor = "=1.0.4"
termion = "=1.5.1"
textwrap = "=0.11.0"
thread-id = "=3.3.0"
thread_local = "=0.3.6"
threadpool = "=1.7.1"
tiff = "=0.2.2"
time = "=0.1.42"
tokio = "=0.1.15"
tokio-current-thread = "=0.1.4"
tokio-executor = "=0.1.6"
tokio-io = "=0.1.11"
tokio-reactor = "=0.1.8"
tokio-tcp = "=0.1.3"
tokio-threadpool = "=0.1.11"
tokio-timer = "=0.2.10"
toml = "=0.4.10"
traitobject = "=0.1.0"
try-lock = "=0.2.2"
ucd-util = "=0.1.3"
unicase = "=2.2.0"
unicode-bidi = "=0.3.4"
unicode-normalization = "=0.1.8"
unicode-width = "=0.1.5"
unicode-xid = "=0.1.0"
unreachable = "=1.0.0"
untrusted = "=0.6.2"
url = "=1.7.2"
utf-8 = "=0.7.5"
utf8-ranges = "=1.0.2"
vcpkg = "=0.2.6"
vec_map = "=0.8.1"
version_check = "=0.1.5"
void = "=1.0.2"
walkdir = "=2.2.7"
want = "=0.0.6"
winapi = "=0.3.6"
winapi-build = "=0.1.1"
winapi-i686-pc-windows-gnu = "=0.4.0"
winapi-util = "=0.1.2"
winapi-x86_64-pc-windows-gnu = "=0.4.0"
wincolor = "=1.0.1"
ws2_32-sys = "=0.2.1"
xattr = "=0.2.2"

[dependencies.serde]
version = "=1.0.88"
features = ["derive", "rc"]

[dependencies.serde_json]
version = "=1.0.38"
features = ["raw_value"]

[dependencies.syn]
version = "=0.15.26"
features = ["extra-traits", "fold", "full", "visit", "visit-mut"]

[dependencies.uuid]
version = "=0.7.2"
features = ["serde", "u128", "v1", "v3", "v4", "v5"]
