[package]
name = "playground"
version = "0.0.1"
authors = ["The Rust Playground"]
[profile.dev]
codegen-units = 1
incremental = false

[profile.release]
codegen-units = 1
incremental = false

[dependencies]
adler32 = "=1.0.3"
aho-corasick = "=0.7.3"
ansi_term = "=0.11.0"
argon2rs = "=0.2.5"
arrayvec = "=0.4.10"
atty = "=0.2.11"
autocfg = "=0.1.4"
backtrace = "=0.3.26"
backtrace-sys = "=0.1.28"
base64 = "=0.10.1"
bit-set = "=0.4.0"
bit-vec = "=0.4.4"
bitflags = "=1.0.4"
blake2-rfc = "=0.2.18"
build_const = "=0.2.1"
byteorder = "=1.3.1"
bytes = "=0.4.12"
cc = "=1.0.37"
cfg-if = "=0.1.9"
chrono = "=0.4.6"
clap = "=2.33.0"
cloudabi = "=0.0.3"
color_quant = "=1.0.1"
constant_time_eq = "=0.1.3"
cookie = "=0.12.0"
cookie_store = "=0.7.0"
crc = "=1.8.1"
crc32fast = "=1.2.0"
crossbeam = "=0.7.1"
crossbeam-channel = "=0.3.8"
crossbeam-deque = "=0.7.1"
crossbeam-epoch = "=0.7.1"
crossbeam-queue = "=0.1.2"
crossbeam-utils = "=0.6.5"
csv = "=1.0.7"
csv-core = "=0.1.5"
data-encoding = "=2.1.2"
debug_unreachable = "=0.1.1"
deflate = "=0.7.19"
dirs = "=1.0.5"
dtoa = "=0.4.4"
either = "=1.5.2"
encoding_rs = "=0.8.17"
env_logger = "=0.6.1"
error-chain = "=0.12.1"
failure = "=0.1.5"
failure_derive = "=0.1.5"
filetime = "=0.2.6"
fixedbitset = "=0.1.9"
flate2 = "=1.0.7"
fnv = "=1.0.6"
foreign-types = "=0.3.2"
foreign-types-shared = "=0.1.1"
fuchsia-cprng = "=0.1.1"
fuchsia-zircon = "=0.3.3"
fuchsia-zircon-sys = "=0.3.3"
futf = "=0.1.4"
futures = "=0.1.27"
futures-cpupool = "=0.1.8"
gcc = "=0.3.55"
gif = "=0.10.1"
glob = "=0.3.0"
h2 = "=0.1.21"
html5ever = "=0.18.0"
http = "=0.1.17"
http-body = "=0.1.0"
httparse = "=1.3.3"
humantime = "=1.2.0"
hyper = "=0.12.29"
hyper-tls = "=0.3.2"
idna = "=0.1.5"
image = "=0.21.1"
indexmap = "=1.0.2"
inflate = "=0.4.5"
iovec = "=0.1.2"
itertools = "=0.8.0"
itoa = "=0.4.4"
jpeg-decoder = "=0.1.15"
kernel32-sys = "=0.2.2"
lazy_static = "=1.3.0"
lazycell = "=1.2.1"
libc = "=0.2.56"
lock_api = "=0.2.0"
log = "=0.4.6"
lzw = "=0.10.0"
mac = "=0.1.1"
markup5ever = "=0.3.2"
matches = "=0.1.8"
memchr = "=2.2.0"
memmap = "=0.7.0"
memoffset = "=0.3.0"
mime = "=0.3.13"
mime_guess = "=2.0.0-alpha.6"
miniz-sys = "=0.1.12"
miniz_oxide = "=0.2.1"
miniz_oxide_c_api = "=0.2.1"
mio = "=0.6.19"
miow = "=0.2.1"
native-tls = "=0.2.3"
net2 = "=0.2.33"
new_debug_unreachable = "=1.0.3"
nodrop = "=0.1.13"
num = "=0.2.0"
num-bigint = "=0.2.2"
num-complex = "=0.2.1"
num-derive = "=0.2.5"
num-integer = "=0.1.41"
num-iter = "=0.1.39"
num-rational = "=0.2.1"
num-traits = "=0.2.8"
num_cpus = "=1.10.0"
numtoa = "=0.1.0"
openssl-probe = "=0.1.2"
ordermap = "=0.3.5"
owning_ref = "=0.4.0"
parking_lot = "=0.8.0"
parking_lot_core = "=0.5.0"
percent-encoding = "=1.0.1"
petgraph = "=0.4.13"
phf = "=0.7.24"
phf_codegen = "=0.7.24"
phf_generator = "=0.7.24"
phf_shared = "=0.7.24"
pkg-config = "=0.3.14"
png = "=0.14.1"
precomputed-hash = "=0.1.1"
proc-macro2 = "=0.4.30"
publicsuffix = "=1.5.2"
quick-error = "=1.2.2"
quote = "=0.6.12"
rand = "=0.6.5"
rand_chacha = "=0.1.1"
rand_core = "=0.4.0"
rand_hc = "=0.1.0"
rand_isaac = "=0.1.1"
rand_jitter = "=0.1.4"
rand_os = "=0.1.3"
rand_pcg = "=0.1.2"
rand_xorshift = "=0.1.1"
rayon = "=1.0.3"
rayon-core = "=1.4.1"
rdrand = "=0.4.0"
regex = "=1.1.6"
regex-syntax = "=0.6.6"
remove_dir_all = "=0.5.1"
reqwest = "=0.9.17"
ring = "=0.14.6"
rustc-demangle = "=0.1.15"
rustc-serialize = "=0.3.24"
rustc_version = "=0.2.3"
ryu = "=0.2.8"
same-file = "=1.0.4"
schannel = "=0.1.15"
scoped_threadpool = "=0.1.9"
scopeguard = "=1.0.0"
select = "=0.4.2"
semver = "=0.9.0"
semver-parser = "=0.9.0"
serde_derive = "=1.0.91"
serde_urlencoded = "=0.5.5"
siphasher = "=0.2.3"
slab = "=0.4.2"
smallvec = "=0.6.9"
spin = "=0.5.0"
stable_deref_trait = "=1.1.1"
string = "=0.1.3"
string_cache = "=0.6.2"
string_cache_codegen = "=0.4.2"
string_cache_shared = "=0.3.0"
strsim = "=0.9.2"
synom = "=0.11.3"
synstructure = "=0.10.2"
syslog = "=4.0.1"
tar = "=0.4.26"
tempdir = "=0.3.7"
tempfile = "=3.0.8"
tendril = "=0.3.1"
term = "=0.5.2"
termcolor = "=1.0.4"
termion = "=1.5.2"
textwrap = "=0.11.0"
thread-id = "=3.3.0"
thread_local = "=0.3.6"
threadpool = "=1.7.1"
tiff = "=0.2.2"
time = "=0.1.42"
tokio = "=0.1.21"
tokio-buf = "=0.1.1"
tokio-current-thread = "=0.1.6"
tokio-executor = "=0.1.7"
tokio-io = "=0.1.12"
tokio-reactor = "=0.1.9"
tokio-sync = "=0.1.5"
tokio-tcp = "=0.1.3"
tokio-threadpool = "=0.1.14"
tokio-timer = "=0.2.11"
tokio-trace-core = "=0.2.0"
toml = "=0.5.1"
try-lock = "=0.2.2"
try_from = "=0.3.2"
ucd-util = "=0.1.3"
unicase = "=2.4.0"
unicode-bidi = "=0.3.4"
unicode-normalization = "=0.1.8"
unicode-width = "=0.1.5"
unicode-xid = "=0.1.0"
unreachable = "=1.0.0"
untrusted = "=0.6.2"
url = "=1.7.2"
utf-8 = "=0.7.5"
utf8-ranges = "=1.0.2"
vcpkg = "=0.2.6"
vec_map = "=0.8.1"
version_check = "=0.9.1"
void = "=1.0.2"
walkdir = "=2.2.7"
want = "=0.0.6"
winapi = "=0.3.7"
winapi-build = "=0.1.1"
winapi-i686-pc-windows-gnu = "=0.4.0"
winapi-util = "=0.1.2"
winapi-x86_64-pc-windows-gnu = "=0.4.0"
wincolor = "=1.0.1"
ws2_32-sys = "=0.2.1"
xattr = "=0.2.2"

[dependencies.serde]
version = "=1.0.91"
features = ["derive", "rc"]

[dependencies.serde_json]
version = "=1.0.39"
features = ["raw_value"]

[dependencies.syn]
version = "=0.15.34"
features = ["extra-traits", "fold", "full", "visit", "visit-mut"]

[dependencies.uuid]
version = "=0.7.4"
features = ["serde", "u128", "v1", "v3", "v4", "v5"]
