
[dependencies]
advapi32-sys = "0.2.0"
aho-corasick = "0.5.2"
ansi_term = "0.8.0"
aster = "0.22.0"
bitflags = "0.7.0"
byteorder = "0.5.3"
cfg-if = "0.1.0"
chrono = "0.2.22"
clap = "2.10.0"
color_quant = "1.0.0"
cookie = "0.2.5"
crossbeam = "0.2.9"
deque = "0.3.1"
docopt = "0.6.81"
dtoa = "0.2.1"
enum_primitive = "0.1.0"
env_logger = "0.3.4"
flate2 = "0.2.14"
gcc = "0.3.32"
gdi32-sys = "0.2.0"
getopts = "0.2.14"
gif = "0.9.0"
gl_generator = "0.5.2"
glob = "0.2.11"
hpack = "0.3.0"
httparse = "1.1.2"
hyper = "0.9.10"
idna = "0.1.0"
image = "0.10.1"
inflate = "0.1.1"
itertools = "0.4.16"
itoa = "0.1.1"
jpeg-decoder = "0.1.6"
kernel32-sys = "0.2.2"
khronos_api = "1.0.0"
language-tags = "0.2.2"
lazy_static = "0.2.1"
libc = "0.2.14"
libz-sys = "1.0.5"
log = "0.3.6"
lzw = "0.10.0"
matches = "0.1.2"
memchr = "0.1.11"
mime = "0.2.1"
miniz-sys = "0.1.7"
net2 = "0.2.26"
nix = "0.6.0"
nom = "1.2.4"
num = "0.1.34"
num-bigint = "0.1.33"
num-complex = "0.1.33"
num-integer = "0.1.32"
num-iter = "0.1.32"
num-rational = "0.1.32"
num-traits = "0.1.34"
num_cpus = "1.0.0"
openssl = "0.7.14"
openssl-sys = "0.7.14"
openssl-sys-extras = "0.7.14"
openssl-verify = "0.1.0"
phf = "0.7.16"
phf_generator = "0.7.16"
phf_shared = "0.7.16"
pkg-config = "0.3.8"
png = "0.5.2"
quasi = "0.16.0"
quasi_codegen = "0.16.0"
rand = "0.3.14"
rayon = "0.4.0"
regex = "0.1.73"
regex-syntax = "0.3.4"
rust-crypto = "0.2.36"
rustc-serialize = "0.3.19"
rustc_version = "0.1.7"
semver = "0.2.3"
serde = "0.8.0"
serde_codegen = "0.8.0"
serde_codegen_internals = "0.5.0"
serde_json = "0.8.0"
shared_library = "0.1.5"
slab = "0.2.0"
solicit = "0.4.4"
strsim = "0.4.1"
syntex = "0.39.0"
syntex_errors = "0.39.0"
syntex_pos = "0.39.0"
syntex_syntax = "0.39.0"
tempdir = "0.3.4"
tempfile = "2.1.4"
term = "0.4.4"
term_size = "0.1.0"
thread-id = "2.0.0"
thread_local = "0.2.6"
time = "0.1.35"
toml = "0.1.30"
traitobject = "0.0.3"
typeable = "0.1.2"
unicase = "1.4.0"
unicode-bidi = "0.2.3"
unicode-normalization = "0.1.2"
unicode-width = "0.1.3"
unicode-xid = "0.0.3"
unsafe-any = "0.4.1"
url = "1.1.1"
user32-sys = "0.2.0"
utf8-ranges = "0.1.3"
uuid = "0.2.3"
vec_map = "0.6.0"
void = "1.0.2"
winapi = "0.2.8"
winapi-build = "0.1.1"
ws2_32-sys = "0.2.1"
xml-rs = "0.3.4"

[package]
authors = ["The Rust Playground"]
name = "playground"
version = "0.0.1"
