[package]
name = "playground"
version = "0.0.1"
authors = ["The Rust Playground"]

[dependencies]
adler32 = "1.0.2"
advapi32-sys = "0.2.0"
aho-corasick = "0.6.4"
ansi_term = "0.10.2"
atty = "0.2.6"
backtrace = "0.3.4"
backtrace-sys = "0.1.16"
base64 = "0.9.0"
bit-set = "0.4.0"
bit-vec = "0.4.4"
bitflags = "1.0.1"
build_const = "0.2.0"
byteorder = "1.2.1"
bytes = "0.4.5"
cc = "1.0.3"
cfg-if = "0.1.2"
chrono = "0.4.0"
clap = "2.29.0"
cmake = "0.1.29"
coco = "0.1.1"
color_quant = "1.0.0"
cookie = "0.10.1"
crc = "1.6.0"
crossbeam = "0.3.0"
crypt32-sys = "0.2.0"
csv = "1.0.0-beta.5"
csv-core = "0.1.3"
data-encoding = "2.1.0"
dbghelp-sys = "0.2.0"
debug_unreachable = "0.1.1"
deflate = "0.7.17"
docopt = "0.8.1"
dtoa = "0.4.2"
either = "1.4.0"
enum_primitive = "0.1.1"
env_logger = "0.5.0-rc.1"
error-chain = "0.11.0"
extprim = "1.4.0"
filetime = "0.1.14"
fixedbitset = "0.1.8"
flate2 = "1.0.1"
foreign-types = "0.3.2"
foreign-types-shared = "0.1.1"
fuchsia-zircon = "0.3.2"
fuchsia-zircon-sys = "0.3.2"
futf = "0.1.3"
futures = "0.1.17"
futures-cpupool = "0.1.7"
gcc = "0.3.54"
getopts = "0.2.15"
gif = "0.9.2"
glob = "0.2.11"
hpack = "0.3.0"
html5ever = "0.18.0"
httparse = "1.2.3"
hyper = "0.11.9"
hyper-tls = "0.1.2"
idna = "0.1.4"
image = "0.18.0"
inflate = "0.3.3"
iovec = "0.1.1"
itertools = "0.7.4"
itoa = "0.3.4"
jpeg-decoder = "0.1.13"
kernel32-sys = "0.2.2"
language-tags = "0.2.2"
lazy_static = "1.0.0"
lazycell = "0.5.1"
libc = "0.2.34"
libflate = "0.1.12"
libz-sys = "1.0.18"
log = "0.4.0-rc.1"
lzw = "0.10.0"
mac = "0.1.1"
markup5ever = "0.3.2"
matches = "0.1.6"
memchr = "2.0.1"
memmap = "0.6.1"
mime = "0.3.5"
mime_guess = "2.0.0-alpha.3"
miniz-sys = "0.1.10"
mio = "0.6.11"
miow = "0.2.1"
native-tls = "0.1.4"
net2 = "0.2.31"
nix = "0.9.0"
num = "0.1.41"
num-bigint = "0.1.41"
num-complex = "0.1.41"
num-integer = "0.1.35"
num-iter = "0.1.34"
num-rational = "0.1.40"
num-traits = "0.1.41"
num_cpus = "1.7.0"
ordermap = "0.3.2"
percent-encoding = "1.0.1"
petgraph = "0.4.10"
phf = "0.7.21"
phf_codegen = "0.7.21"
phf_generator = "0.7.21"
phf_shared = "0.7.21"
pkg-config = "0.3.9"
png = "0.11.0"
precomputed-hash = "0.1.1"
quote = "0.3.15"
rand = "0.4.1"
rayon = "0.9.0"
rayon-core = "1.3.0"
regex = "0.2.3"
regex-syntax = "0.4.1"
relay = "0.1.0"
reqwest = "0.8.2"
rustc-demangle = "0.1.5"
rustc-serialize = "0.3.24"
rustc_version = "0.2.1"
safemem = "0.2.0"
same-file = "1.0.0"
schannel = "0.1.9"
scoped-tls = "0.1.0"
scoped_threadpool = "0.1.8"
scopeguard = "0.3.3"
secur32-sys = "0.2.0"
select = "0.4.2"
semver = "0.9.0"
semver-parser = "0.7.0"
serde = "1.0.24"
serde_codegen_internals = "0.14.2"
serde_derive = "1.0.24"
serde_derive_internals = "0.18.0"
serde_json = "1.0.8"
serde_urlencoded = "0.5.1"
siphasher = "0.2.2"
slab = "0.4.0"
smallvec = "0.2.1"
solicit = "0.4.4"
string_cache = "0.6.2"
string_cache_codegen = "0.4.0"
string_cache_shared = "0.3.0"
strsim = "0.6.0"
syn = "0.11.11"
synom = "0.11.3"
syntex_errors = "0.59.1"
syntex_pos = "0.59.1"
syntex_syntax = "0.59.1"
syslog = "3.3.0"
take = "0.1.0"
tar = "0.4.14"
tempdir = "0.3.5"
tendril = "0.3.1"
term = "0.4.6"
term_size = "1.0.0-beta1"
termcolor = "0.3.3"
termion = "1.5.1"
textwrap = "0.9.0"
thread-id = "3.2.0"
thread_local = "0.3.5"
threadpool = "1.7.1"
time = "0.1.38"
tokio-core = "0.1.11"
tokio-io = "0.1.4"
tokio-proto = "0.1.1"
tokio-service = "0.1.0"
tokio-tls = "0.1.3"
toml = "0.4.5"
traitobject = "0.1.0"
typeable = "0.1.2"
unicase = "2.1.0"
unicode-bidi = "0.3.4"
unicode-normalization = "0.1.5"
unicode-segmentation = "1.2.0"
unicode-width = "0.1.4"
unicode-xid = "0.1.0"
unix_socket = "0.5.0"
unreachable = "1.0.0"
url = "1.6.0"
utf-8 = "0.7.1"
utf8-ranges = "1.0.0"
uuid = "0.5.1"
vcpkg = "0.2.2"
vec_map = "0.8.0"
version_check = "0.1.3"
void = "1.0.2"
walkdir = "2.0.1"
winapi = "0.3.2"
winapi-build = "0.1.1"
winapi-i686-pc-windows-gnu = "0.3.1"
winapi-x86_64-pc-windows-gnu = "0.3.1"
wincolor = "0.1.4"
ws2_32-sys = "0.2.1"
xattr = "0.1.11"
xml-rs = "0.7.0"
