[package]
name = "playground"
version = "0.0.1"
authors = ["The Rust Playground"]
[profile.dev]
codegen-units = 1
incremental = false

[profile.release]
codegen-units = 1
incremental = false

[dependencies]
adler32 = "=1.0.3"
aho-corasick = "=0.6.9"
ansi_term = "=0.11.0"
arrayvec = "=0.4.7"
atty = "=0.2.11"
backtrace = "=0.3.9"
backtrace-sys = "=0.1.24"
base64 = "=0.10.0"
bit-set = "=0.4.0"
bit-vec = "=0.4.4"
bitflags = "=1.0.4"
build_const = "=0.2.1"
byteorder = "=1.2.7"
bytes = "=0.4.10"
cc = "=1.0.25"
cfg-if = "=0.1.6"
chrono = "=0.4.6"
clap = "=2.32.0"
cloudabi = "=0.0.3"
color_quant = "=1.0.1"
crc = "=1.8.1"
crossbeam = "=0.5.0"
crossbeam-channel = "=0.3.1"
crossbeam-deque = "=0.6.2"
crossbeam-epoch = "=0.6.1"
crossbeam-utils = "=0.6.1"
csv = "=1.0.2"
csv-core = "=0.1.4"
data-encoding = "=2.1.1"
debug_unreachable = "=0.1.1"
deflate = "=0.7.19"
dtoa = "=0.4.3"
either = "=1.5.0"
encoding_rs = "=0.8.10"
env_logger = "=0.6.0"
error-chain = "=0.12.0"
extprim = "=1.6.0"
filetime = "=0.2.3"
fixedbitset = "=0.1.9"
flate2 = "=1.0.4"
fnv = "=1.0.6"
foreign-types = "=0.3.2"
foreign-types-shared = "=0.1.1"
fuchsia-zircon = "=0.3.3"
fuchsia-zircon-sys = "=0.3.3"
futf = "=0.1.4"
futures = "=0.1.25"
futures-cpupool = "=0.1.8"
gcc = "=0.3.55"
getopts = "=0.2.18"
gif = "=0.10.1"
glob = "=0.2.11"
h2 = "=0.1.13"
html5ever = "=0.18.0"
http = "=0.1.13"
httparse = "=1.3.3"
humantime = "=1.1.1"
hyper = "=0.12.14"
hyper-tls = "=0.3.1"
idna = "=0.1.5"
image = "=0.20.1"
indexmap = "=1.0.2"
inflate = "=0.4.3"
iovec = "=0.1.2"
itertools = "=0.7.8"
itoa = "=0.4.3"
jpeg-decoder = "=0.1.15"
kernel32-sys = "=0.2.2"
language-tags = "=0.2.2"
lazy_static = "=1.2.0"
lazycell = "=1.2.0"
libc = "=0.2.43"
libflate = "=0.1.18"
lock_api = "=0.1.4"
log = "=0.4.6"
lzw = "=0.10.0"
mac = "=0.1.1"
markup5ever = "=0.3.2"
matches = "=0.1.8"
memchr = "=2.1.1"
memmap = "=0.7.0"
memoffset = "=0.2.1"
mime = "=0.3.12"
mime_guess = "=2.0.0-alpha.6"
miniz-sys = "=0.1.11"
miniz_oxide = "=0.2.0"
miniz_oxide_c_api = "=0.2.0"
mio = "=0.6.16"
mio-uds = "=0.6.7"
miow = "=0.2.1"
native-tls = "=0.2.2"
net2 = "=0.2.33"
new_debug_unreachable = "=1.0.1"
nodrop = "=0.1.13"
num = "=0.2.0"
num-bigint = "=0.2.1"
num-complex = "=0.2.1"
num-derive = "=0.2.3"
num-integer = "=0.1.39"
num-iter = "=0.1.37"
num-rational = "=0.2.1"
num-traits = "=0.2.6"
num_cpus = "=1.8.0"
openssl-probe = "=0.1.2"
ordermap = "=0.3.5"
owning_ref = "=0.3.3"
parking_lot = "=0.6.4"
parking_lot_core = "=0.3.1"
percent-encoding = "=1.0.1"
petgraph = "=0.4.13"
phf = "=0.7.23"
phf_codegen = "=0.7.23"
phf_generator = "=0.7.23"
phf_shared = "=0.7.23"
pkg-config = "=0.3.14"
png = "=0.12.0"
precomputed-hash = "=0.1.1"
proc-macro2 = "=0.4.23"
quick-error = "=1.2.2"
quote = "=0.6.10"
rand = "=0.6.0"
rand_chacha = "=0.1.0"
rand_core = "=0.3.0"
rand_hc = "=0.1.0"
rand_isaac = "=0.1.0"
rand_pcg = "=0.1.1"
rand_xorshift = "=0.1.0"
rayon = "=1.0.3"
rayon-core = "=1.4.1"
regex = "=1.0.6"
regex-syntax = "=0.6.3"
remove_dir_all = "=0.5.1"
reqwest = "=0.9.5"
ring = "=0.13.3"
rustc-demangle = "=0.1.9"
rustc-serialize = "=0.3.24"
rustc_version = "=0.2.3"
ryu = "=0.2.7"
safemem = "=0.3.0"
same-file = "=1.0.4"
schannel = "=0.1.14"
scoped_threadpool = "=0.1.9"
scopeguard = "=0.3.3"
select = "=0.4.2"
semver = "=0.9.0"
semver-parser = "=0.9.0"
serde = "=1.0.80"
serde_derive = "=1.0.80"
serde_derive_internals = "=0.23.1"
serde_urlencoded = "=0.5.3"
siphasher = "=0.2.3"
slab = "=0.4.1"
smallvec = "=0.6.5"
stable_deref_trait = "=1.1.1"
string = "=0.1.1"
string_cache = "=0.6.2"
string_cache_codegen = "=0.4.2"
string_cache_shared = "=0.3.0"
strsim = "=0.8.0"
synom = "=0.11.3"
syntex_errors = "=0.59.1"
syntex_pos = "=0.59.1"
syntex_syntax = "=0.59.1"
syslog = "=4.0.1"
tar = "=0.4.20"
tempdir = "=0.3.7"
tempfile = "=3.0.4"
tendril = "=0.3.1"
term = "=0.5.1"
termcolor = "=1.0.4"
termion = "=1.5.1"
textwrap = "=0.10.0"
thread-id = "=3.3.0"
thread_local = "=0.3.6"
threadpool = "=1.7.1"
tiff = "=0.2.1"
time = "=0.1.40"
tokio = "=0.1.11"
tokio-codec = "=0.1.1"
tokio-current-thread = "=0.1.3"
tokio-executor = "=0.1.5"
tokio-fs = "=0.1.4"
tokio-io = "=0.1.10"
tokio-reactor = "=0.1.6"
tokio-tcp = "=0.1.2"
tokio-threadpool = "=0.1.8"
tokio-timer = "=0.2.7"
tokio-udp = "=0.1.2"
tokio-uds = "=0.2.3"
toml = "=0.4.8"
traitobject = "=0.1.0"
try-lock = "=0.2.2"
typeable = "=0.1.2"
ucd-util = "=0.1.2"
unicase = "=2.2.0"
unicode-bidi = "=0.3.4"
unicode-normalization = "=0.1.7"
unicode-width = "=0.1.5"
unicode-xid = "=0.1.0"
unreachable = "=1.0.0"
untrusted = "=0.6.2"
url = "=1.7.2"
utf-8 = "=0.7.4"
utf8-ranges = "=1.0.2"
vcpkg = "=0.2.6"
vec_map = "=0.8.1"
version_check = "=0.1.5"
void = "=1.0.2"
walkdir = "=2.2.7"
want = "=0.0.6"
winapi = "=0.3.6"
winapi-build = "=0.1.1"
winapi-i686-pc-windows-gnu = "=0.4.0"
winapi-util = "=0.1.1"
winapi-x86_64-pc-windows-gnu = "=0.4.0"
wincolor = "=1.0.1"
ws2_32-sys = "=0.2.1"
xattr = "=0.2.2"

[dependencies.serde_json]
version = "=1.0.33"
features = ["raw_value"]

[dependencies.syn]
version = "=0.15.20"
features = ["extra-traits", "fold", "full", "visit", "visit-mut"]

[dependencies.uuid]
version = "=0.7.1"
features = ["serde", "u128", "v1", "v3", "v4", "v5"]
