[package]
name = "playground"
version = "0.0.1"
authors = ["The Rust Playground"]
[profile.dev]
codegen-units = 1
incremental = false

[profile.release]
codegen-units = 1
incremental = false

[dependencies]
adler32 = "=1.0.4"
aho-corasick = "=0.7.6"
alga = "=0.9.1"
ansi_term = "=0.12.1"
antidote = "=1.0.0"
approx = "=0.3.2"
arc-swap = "=0.3.11"
arrayref = "=0.3.5"
arrayvec = "=0.5.1"
atty = "=0.2.13"
autocfg = "=0.1.6"
backtrace = "=0.3.38"
backtrace-sys = "=0.1.31"
base64 = "=0.10.1"
bit-set = "=0.5.1"
bit-vec = "=0.5.1"
bitflags = "=1.2.1"
blake2b_simd = "=0.5.8"
block-buffer = "=0.3.3"
bstr = "=0.2.8"
bumpalo = "=2.6.0"
byte-tools = "=0.2.0"
byteorder = "=1.3.2"
bytes = "=0.4.12"
c2-chacha = "=0.2.2"
cc = "=1.0.45"
cfg-if = "=0.1.10"
clap = "=2.33.0"
cloudabi = "=0.0.3"
color_quant = "=1.0.1"
constant_time_eq = "=0.1.4"
cookie = "=0.12.0"
cookie_store = "=0.7.0"
crc32fast = "=1.2.0"
crossbeam = "=0.7.2"
crossbeam-channel = "=0.3.9"
crossbeam-deque = "=0.7.1"
crossbeam-epoch = "=0.7.2"
crossbeam-queue = "=0.1.2"
crossbeam-utils = "=0.6.6"
crypto-mac = "=0.5.2"
csv = "=1.1.1"
csv-core = "=0.1.6"
data-encoding = "=2.1.2"
deflate = "=0.7.20"
digest = "=0.7.6"
dirs = "=2.0.2"
dirs-sys = "=0.3.4"
dtoa = "=0.4.4"
either = "=1.5.3"
encoding_rs = "=0.8.20"
env_logger = "=0.7.0"
error-chain = "=0.12.1"
failure = "=0.1.6"
failure_derive = "=0.1.6"
fake-simd = "=0.1.2"
fallible-iterator = "=0.2.0"
fallible-streaming-iterator = "=0.1.9"
filetime = "=0.2.7"
flate2 = "=1.0.12"
fnv = "=1.0.6"
foreign-types = "=0.3.2"
foreign-types-shared = "=0.1.1"
fuchsia-cprng = "=0.1.1"
fuchsia-zircon = "=0.3.3"
fuchsia-zircon-sys = "=0.3.3"
futf = "=0.1.4"
futures = "=0.1.29"
futures-cpupool = "=0.1.8"
gcc = "=0.3.55"
generic-array = "=0.12.3"
getrandom = "=0.1.12"
gif = "=0.10.3"
glob = "=0.3.0"
h2 = "=0.1.26"
heck = "=0.3.1"
hex = "=0.2.0"
hmac = "=0.5.0"
html5ever = "=0.23.0"
http = "=0.1.18"
http-body = "=0.1.0"
httparse = "=1.3.4"
humantime = "=1.3.0"
hyper = "=0.12.35"
hyper-tls = "=0.3.2"
idna = "=0.2.0"
image = "=0.22.3"
indexmap = "=1.2.0"
inflate = "=0.4.5"
iovec = "=0.1.4"
itertools = "=0.8.0"
itoa = "=0.4.4"
jpeg-decoder = "=0.1.16"
js-sys = "=0.3.28"
kernel32-sys = "=0.2.2"
lazy_static = "=1.4.0"
lazycell = "=1.2.1"
libc = "=0.2.64"
libm = "=0.1.4"
libsqlite3-sys = "=0.16.0"
linked-hash-map = "=0.5.2"
lock_api = "=0.3.1"
log = "=0.4.8"
log-mdc = "=0.1.0"
log4rs = "=0.8.3"
lru-cache = "=0.1.2"
lzw = "=0.10.0"
mac = "=0.1.1"
markup5ever = "=0.8.1"
matches = "=0.1.8"
matrixmultiply = "=0.2.3"
md5 = "=0.3.8"
memchr = "=2.2.1"
memmap = "=0.7.0"
memoffset = "=0.5.1"
mime = "=0.3.14"
mime_guess = "=2.0.1"
miniz_oxide = "=0.3.3"
mio = "=0.6.19"
miow = "=0.2.1"
nalgebra = "=0.18.1"
native-tls = "=0.2.3"
ndarray = "=0.13.0"
net2 = "=0.2.33"
new_debug_unreachable = "=1.0.3"
nodrop = "=0.1.14"
nom = "=4.2.3"
num = "=0.2.0"
num-bigint = "=0.2.3"
num-complex = "=0.2.3"
num-derive = "=0.2.5"
num-integer = "=0.1.41"
num-iter = "=0.1.39"
num-rational = "=0.2.2"
num-traits = "=0.2.8"
num_cpus = "=1.10.1"
openssl = "=0.10.25"
openssl-probe = "=0.1.2"
openssl-sys = "=0.9.51"
ordered-float = "=1.0.2"
parking_lot = "=0.9.0"
parking_lot_core = "=0.6.2"
percent-encoding = "=2.1.0"
phf = "=0.7.24"
phf_codegen = "=0.7.24"
phf_generator = "=0.7.24"
phf_shared = "=0.7.24"
pkg-config = "=0.3.16"
png = "=0.15.0"
postgres = "=0.15.2"
postgres-protocol = "=0.3.2"
postgres-shared = "=0.4.2"
ppv-lite86 = "=0.2.5"
precomputed-hash = "=0.1.1"
proc-macro2 = "=1.0.5"
publicsuffix = "=1.5.3"
quick-error = "=1.2.2"
quote = "=1.0.2"
rand = "=0.7.2"
rand_chacha = "=0.2.1"
rand_core = "=0.5.1"
rand_hc = "=0.2.0"
rand_isaac = "=0.1.1"
rand_jitter = "=0.1.4"
rand_os = "=0.1.3"
rand_pcg = "=0.1.2"
rand_xorshift = "=0.1.1"
rawpointer = "=0.2.1"
rayon = "=1.2.0"
rayon-core = "=1.6.0"
rdrand = "=0.4.0"
regex = "=1.3.1"
regex-automata = "=0.1.8"
regex-syntax = "=0.6.12"
remove_dir_all = "=0.5.2"
reqwest = "=0.9.22"
ring = "=0.16.9"
rusqlite = "=0.20.0"
rust-argon2 = "=0.5.1"
rustc-demangle = "=0.1.16"
rustc-serialize = "=0.3.24"
rustc_version = "=0.2.3"
ryu = "=1.0.2"
safemem = "=0.2.0"
same-file = "=1.0.5"
schannel = "=0.1.16"
scoped_threadpool = "=0.1.9"
scopeguard = "=1.0.0"
select = "=0.4.3"
semver = "=0.9.0"
semver-parser = "=0.9.0"
serde-value = "=0.5.3"
serde_derive = "=1.0.101"
serde_urlencoded = "=0.5.5"
serde_yaml = "=0.8.11"
sha2 = "=0.7.1"
siphasher = "=0.2.3"
slab = "=0.4.2"
smallvec = "=0.6.10"
socket2 = "=0.3.11"
sourcefile = "=0.1.4"
spin = "=0.5.2"
string = "=0.2.1"
string_cache = "=0.7.4"
string_cache_codegen = "=0.4.4"
string_cache_shared = "=0.3.0"
stringprep = "=0.1.2"
strsim = "=0.9.2"
synstructure = "=0.12.1"
syslog = "=4.0.1"
tar = "=0.4.26"
tempdir = "=0.3.7"
tempfile = "=3.1.0"
tendril = "=0.4.1"
term = "=0.6.1"
termcolor = "=1.0.5"
textwrap = "=0.11.0"
thread-id = "=3.3.0"
thread_local = "=1.0.0"
threadpool = "=1.7.1"
tiff = "=0.3.1"
time = "=0.1.42"
tokio = "=0.1.22"
tokio-buf = "=0.1.1"
tokio-current-thread = "=0.1.6"
tokio-executor = "=0.1.8"
tokio-io = "=0.1.12"
tokio-reactor = "=0.1.10"
tokio-sync = "=0.1.7"
tokio-tcp = "=0.1.3"
tokio-threadpool = "=0.1.16"
tokio-timer = "=0.2.11"
toml = "=0.5.3"
traitobject = "=0.1.0"
try-lock = "=0.2.2"
try_from = "=0.3.2"
typemap = "=0.3.3"
typenum = "=1.11.2"
ucd-util = "=0.1.5"
unicase = "=2.5.1"
unicode-bidi = "=0.3.4"
unicode-normalization = "=0.1.8"
unicode-segmentation = "=1.3.0"
unicode-width = "=0.1.6"
unicode-xid = "=0.2.0"
unreachable = "=1.0.0"
unsafe-any = "=0.4.2"
untrusted = "=0.7.0"
url = "=2.1.0"
utf-8 = "=0.7.5"
utf8-ranges = "=1.0.4"
vcpkg = "=0.2.7"
vec_map = "=0.8.1"
version_check = "=0.9.1"
void = "=1.0.2"
walkdir = "=2.2.9"
want = "=0.2.0"
wasi = "=0.7.0"
wasm-bindgen = "=0.2.51"
wasm-bindgen-backend = "=0.2.51"
wasm-bindgen-macro = "=0.2.51"
wasm-bindgen-macro-support = "=0.2.51"
wasm-bindgen-shared = "=0.2.51"
wasm-bindgen-webidl = "=0.2.51"
web-sys = "=0.3.28"
weedle = "=0.10.0"
winapi = "=0.3.8"
winapi-build = "=0.1.1"
winapi-i686-pc-windows-gnu = "=0.4.0"
winapi-util = "=0.1.2"
winapi-x86_64-pc-windows-gnu = "=0.4.0"
wincolor = "=1.0.2"
ws2_32-sys = "=0.2.1"
xattr = "=0.2.2"
yaml-rust = "=0.4.3"

[dependencies.chrono]
version = "=0.4.9"
features = ["wasmbind"]

[dependencies.serde]
version = "=1.0.101"
features = ["derive", "rc"]

[dependencies.serde_json]
version = "=1.0.41"
features = ["raw_value"]

[dependencies.syn]
version = "=1.0.5"
features = ["extra-traits", "fold", "full", "visit", "visit-mut"]

[dependencies.uuid]
version = "=0.7.4"
features = ["serde", "u128", "v1", "v3", "v4", "v5"]
