[package]
name = "playground"
version = "0.0.1"
authors = ["The Rust Playground"]

[dependencies]
adler32 = "1.0.2"
advapi32-sys = "0.2.0"
aho-corasick = "0.6.3"
ansi_term = "0.10.2"
atty = "0.2.3"
backtrace = "0.3.3"
backtrace-sys = "0.1.16"
base64 = "0.7.0"
bit-set = "0.4.0"
bit-vec = "0.4.4"
bitflags = "1.0.0"
build_const = "0.2.0"
byteorder = "1.1.0"
bytes = "0.4.5"
cc = "1.0.1"
cfg-if = "0.1.2"
chrono = "0.4.0"
clap = "2.26.2"
cmake = "0.1.26"
coco = "0.1.1"
color_quant = "1.0.0"
conv = "0.3.3"
cookie = "0.10.1"
crc = "1.5.0"
crc-core = "0.1.0"
crossbeam = "0.3.0"
crypt32-sys = "0.2.0"
csv = "1.0.0-beta.5"
csv-core = "0.1.3"
custom_derive = "0.1.7"
data-encoding = "2.0.0-rc.2"
dbghelp-sys = "0.2.0"
debug_unreachable = "0.1.1"
deflate = "0.7.17"
docopt = "0.8.1"
dtoa = "0.4.2"
either = "1.2.0"
enum_primitive = "0.1.1"
env_logger = "0.4.3"
error-chain = "0.11.0"
extprim = "1.4.0"
filetime = "0.1.14"
fixedbitset = "0.1.8"
flate2 = "0.2.20"
foreign-types = "0.2.0"
fs2 = "0.4.2"
fuchsia-zircon = "0.2.1"
fuchsia-zircon-sys = "0.2.0"
futf = "0.1.3"
futures = "0.1.16"
futures-cpupool = "0.1.7"
gcc = "0.3.54"
gdi32-sys = "0.2.0"
getopts = "0.2.15"
gif = "0.9.2"
glob = "0.2.11"
hpack = "0.3.0"
html5ever = "0.18.0"
httparse = "1.2.3"
hyper = "0.11.6"
hyper-tls = "0.1.2"
idna = "0.1.4"
image = "0.17.0"
inflate = "0.3.3"
iovec = "0.1.1"
itertools = "0.7.1"
itoa = "0.3.4"
jpeg-decoder = "0.1.13"
kernel32-sys = "0.2.2"
language-tags = "0.2.2"
lazy_static = "0.2.9"
lazycell = "0.5.1"
libc = "0.2.32"
libflate = "0.1.12"
libz-sys = "1.0.18"
log = "0.3.8"
lzw = "0.10.0"
mac = "0.1.1"
magenta = "0.1.1"
magenta-sys = "0.1.1"
markup5ever = "0.3.2"
matches = "0.1.6"
memchr = "1.0.1"
memmap = "0.5.2"
mime = "0.3.5"
mime_guess = "2.0.0-alpha.2"
miniz-sys = "0.1.10"
mio = "0.6.10"
miow = "0.2.1"
native-tls = "0.1.4"
net2 = "0.2.31"
nix = "0.9.0"
num = "0.1.40"
num-bigint = "0.1.40"
num-complex = "0.1.40"
num-integer = "0.1.35"
num-iter = "0.1.34"
num-rational = "0.1.39"
num-traits = "0.1.40"
num_cpus = "1.7.0"
ordermap = "0.3.0"
percent-encoding = "1.0.0"
petgraph = "0.4.10"
phf = "0.7.21"
phf_codegen = "0.7.21"
phf_generator = "0.7.21"
phf_shared = "0.7.21"
pkg-config = "0.3.9"
png = "0.11.0"
precomputed-hash = "0.1.1"
quick-error = "1.2.1"
quote = "0.3.15"
rand = "0.3.17"
rayon = "0.8.2"
rayon-core = "1.2.1"
regex = "0.2.2"
regex-syntax = "0.4.1"
relay = "0.1.0"
reqwest = "0.8.0"
ring = "0.12.1"
rustc-demangle = "0.1.5"
rustc-serialize = "0.3.24"
rustc_version = "0.2.1"
safemem = "0.2.0"
same-file = "0.1.3"
schannel = "0.1.8"
scoped-tls = "0.1.0"
scoped_threadpool = "0.1.8"
scopeguard = "0.3.3"
secur32-sys = "0.2.0"
select = "0.4.2"
semver = "0.8.0"
semver-parser = "0.7.0"
serde = "1.0.15"
serde_codegen = "0.9.0"
serde_codegen_internals = "0.14.2"
serde_derive = "1.0.15"
serde_derive_internals = "0.16.0"
serde_json = "1.0.4"
serde_urlencoded = "0.5.1"
siphasher = "0.2.2"
slab = "0.4.0"
smallvec = "0.2.1"
solicit = "0.4.4"
string_cache = "0.6.2"
string_cache_codegen = "0.4.0"
string_cache_shared = "0.3.0"
strsim = "0.6.0"
syn = "0.11.11"
synom = "0.11.3"
syntex = "0.58.1"
syntex_errors = "0.59.1"
syntex_pos = "0.59.1"
syntex_syntax = "0.59.1"
syslog = "3.3.0"
take = "0.1.0"
tar = "0.4.13"
tempdir = "0.3.5"
tendril = "0.3.1"
term = "0.4.6"
term_size = "0.3.0"
termion = "1.5.1"
textwrap = "0.8.0"
thread-id = "3.2.0"
thread_local = "0.3.4"
threadpool = "1.7.0"
time = "0.1.38"
tokio-core = "0.1.10"
tokio-io = "0.1.3"
tokio-proto = "0.1.1"
tokio-service = "0.1.0"
tokio-tls = "0.1.3"
toml = "0.4.5"
traitobject = "0.1.0"
typeable = "0.1.2"
unicase = "2.0.0"
unicode-bidi = "0.3.4"
unicode-normalization = "0.1.5"
unicode-segmentation = "1.2.0"
unicode-width = "0.1.4"
unicode-xid = "0.1.0"
unix_socket = "0.5.0"
unreachable = "1.0.0"
untrusted = "0.5.1"
url = "1.5.1"
user32-sys = "0.2.0"
utf-8 = "0.7.1"
utf8-ranges = "1.0.0"
uuid = "0.5.1"
vcpkg = "0.2.2"
vec_map = "0.8.0"
version_check = "0.1.3"
void = "1.0.2"
walkdir = "1.0.7"
winapi = "0.2.8"
winapi-build = "0.1.1"
ws2_32-sys = "0.2.1"
xattr = "0.1.11"
xml-rs = "0.6.2"
