blacklist = [
    # Requires native dependencies
    "libressl-pnacl-sys",
    "pnacl-build-helper",

    # Not supported on stable
    "aster",
    "quasi",
    "quasi_codegen",
    "quasi_macros",

    # Apparently deleted
    "serde_macros",
    # Deprecated, causes old versions
    "serde_codegen",

    # Ecosystem is fragmented, only pull in via dependencies
    "openssl",
    "openssl-sys",
    "openssl-sys-extras",
    "openssl-verify",

    # Not supported on stable
    "redox_syscall",
    "redox_termios",
    "redox_users",

    # Not available on Linux
    "security-framework",
    "security-framework-sys",
    "core-foundation",
    "core-foundation-sys",

    # Not supported on stable
    "pin-api",
]

additions = [
    # From the Rust Cookbook
    "ansi_term",
    "base64",
    "bitflags",
    "byteorder",
    "cc",
    "chrono",
    "clap",
    "crossbeam",
    "csv",
    "data-encoding",
    "env_logger",
    "flate2",
    "glob",
    "image",
    "lazy_static",
    "log",
    "log4rs",
    "memmap",
    "mime",
    "nalgebra",
    "ndarray",
    "num",
    "num_cpus",
    "postgres",
    "rand",
    "rayon",
    "regex",
    "reqwest",
    "ring",
    "rusqlite",
    "same-file",
    "select",
    "semver",
    "serde",
    "serde_json",
    "syslog",
    "tar",
    "tempdir",
    "threadpool",
    "toml",
    "unicode-segmentation",
    "url",
    "walkdir",
]
