blacklist = [
    # Not supported on stable
    "redox_syscall",
    "redox_users",

    # # Not available on Linux
    "core-foundation",
    "core-foundation-sys",
    "security-framework",
    "security-framework-sys",
    "winreg",
]

additions = []
