blacklist = [
    # Not supported on stable
    "redox_syscall",
    "redox_users",

    # # Not available on Linux
    "core-foundation",
    "core-foundation-sys",
    "security-framework",
    "security-framework-sys",
    "winreg",
]

additions = [
    # From the Rust Cookbook
    "ansi_term",
    "base64",
    "bitflags",
    "byteorder",
    "cc",
    "chrono",
    "clap",
    "crossbeam",
    "csv",
    "data-encoding",
    "env_logger",
    "flate2",
    "glob",
    "image",
    "lazy_static",
    "log",
    "log4rs",
    "memmap",
    "mime",
    "nalgebra",
    "ndarray",
    "num",
    "num_cpus",
    "postgres",
    "rand",
    "rayon",
    "regex",
    "reqwest",
    "ring",
    "rusqlite",
    "same-file",
    "select",
    "semver",
    "serde",
    "serde_json",
    "syslog",
    "tar",
    "tempdir",
    "threadpool",
    "toml",
    "unicode-segmentation",
    "url",
    "walkdir",
]
