[package]
authors = ["Jake Goulding <jake.goulding@integer32.com>"]
name = "ui"
version = "0.1.0"

[features]
default = ['fork-bomb-prevention']
fork-bomb-prevention = []

[dependencies]
bodyparser = "0.8.0"
corsware = "0.2.0"
env_logger = "0.4.0"
iron = "0.6.0"
lazy_static = "1.0.0"
log = "0.3.6"
mktemp = "0.3.1"
mount = "0.4.0"
petgraph = "0.4.11"
quick-error = "1.1.0"
regex = "0.2.2"
rustc-demangle = "0.1.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
url = "1.4.0"

[dependencies.playground-middleware]
git = "https://github.com/integer32llc/playground-middleware"
