[package]
authors = ["Jake Goulding <jake.goulding@integer32.com>"]
name = "ui"
version = "0.1.0"
build = "build.rs"

[build-dependencies]
serde_codegen = "*"

[dependencies]
bodyparser = "0.3.0"
env_logger = "0.3.3"
iron = "0.3.0"
log = "0.3.6"
mktemp = "0.1.2"
mount = "0.1.0"
quick-error = "1.1.0"
serde = "0.7.10"
serde_json = "0.7.1"
staticfile = { version = "0.2.0", features = ["cache"] }
