[package]
authors = ["Jake Goulding <jake.goulding@integer32.com>"]
name = "ui"
version = "0.1.0"
edition = "2018"

[features]
default = ['fork-bomb-prevention']
fork-bomb-prevention = []

[dependencies]
async-trait = "0.1.52"
axum = { version = "0.5", features = ["headers"] }
dotenv = "0.15.0"
env_logger = "0.9.0"
futures = "0.3.21"
lazy_static = "1.0.0"
log = "0.4.0"
octocrab = "0.15.0"
openssl-probe = "0.1.2"
petgraph = "0.6.0"
prometheus = "0.13.0"
regex = "1.0.0"
rustc-demangle = "0.1.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
snafu = "0.7.0"
strum = { version = "0.24.0", features = ["derive"] }
tempdir = "0.3.7"
tokio = { version = "1.9", features = ["macros", "time", "process", "rt-multi-thread"] }
tower-http = { version = "0.2.2", features = ["cors", "fs", "set-header", "trace"] }
